george@Xubuntu1804:~/Desktop/desktop/django_code/wsgi_test$ python middleware.py 
middleware.py:42: DeprecationWarning: cgi.parse_qs is deprecated, use urllib.parse.parse_qs instead
  parameters = parse_qs(environ.get('QUERY_STRING', ''))
127.0.0.1 - - [26/Apr/2019 20:57:38] "GET / HTTP/1.1" 500 0
Traceback (most recent call last):
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 266, in write
    "write() argument must be a bytes instance"
AssertionError: write() argument must be a bytes instance
127.0.0.1 - - [26/Apr/2019 20:57:38] "GET / HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 41368)
Traceback (most recent call last):
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 266, in write
    "write() argument must be a bytes instance"
AssertionError: write() argument must be a bytes instance

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 141, in run
    self.handle_error()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 368, in handle_error
    self.finish_response()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/simple_server.py", line 133, in handle
    handler.run(self.server.get_app())
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 144, in run
    self.close()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------
127.0.0.1 - - [26/Apr/2019 20:57:38] "GET / HTTP/1.1" 500 0
Traceback (most recent call last):
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 266, in write
    "write() argument must be a bytes instance"
AssertionError: write() argument must be a bytes instance
127.0.0.1 - - [26/Apr/2019 20:57:38] "GET / HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 41370)
Traceback (most recent call last):
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 266, in write
    "write() argument must be a bytes instance"
AssertionError: write() argument must be a bytes instance

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 141, in run
    self.handle_error()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 368, in handle_error
    self.finish_response()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/simple_server.py", line 133, in handle
    handler.run(self.server.get_app())
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 144, in run
    self.close()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------
127.0.0.1 - - [26/Apr/2019 20:57:38] "GET / HTTP/1.1" 500 0
Traceback (most recent call last):
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 266, in write
    "write() argument must be a bytes instance"
AssertionError: write() argument must be a bytes instance
127.0.0.1 - - [26/Apr/2019 20:57:38] "GET / HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 41372)
Traceback (most recent call last):
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 266, in write
    "write() argument must be a bytes instance"
AssertionError: write() argument must be a bytes instance

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 141, in run
    self.handle_error()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 368, in handle_error
    self.finish_response()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/simple_server.py", line 133, in handle
    handler.run(self.server.get_app())
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 144, in run
    self.close()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------
127.0.0.1 - - [26/Apr/2019 20:57:38] "GET / HTTP/1.1" 500 0
Traceback (most recent call last):
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 266, in write
    "write() argument must be a bytes instance"
AssertionError: write() argument must be a bytes instance
127.0.0.1 - - [26/Apr/2019 20:57:38] "GET / HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 41374)
Traceback (most recent call last):
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 266, in write
    "write() argument must be a bytes instance"
AssertionError: write() argument must be a bytes instance

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 141, in run
    self.handle_error()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 368, in handle_error
    self.finish_response()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/simple_server.py", line 133, in handle
    handler.run(self.server.get_app())
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 144, in run
    self.close()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------
127.0.0.1 - - [26/Apr/2019 20:57:38] "GET / HTTP/1.1" 500 0
Traceback (most recent call last):
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 266, in write
    "write() argument must be a bytes instance"
AssertionError: write() argument must be a bytes instance
127.0.0.1 - - [26/Apr/2019 20:57:38] "GET / HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 41376)
Traceback (most recent call last):
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 266, in write
    "write() argument must be a bytes instance"
AssertionError: write() argument must be a bytes instance

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 141, in run
    self.handle_error()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 368, in handle_error
    self.finish_response()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/simple_server.py", line 133, in handle
    handler.run(self.server.get_app())
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 144, in run
    self.close()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------
127.0.0.1 - - [26/Apr/2019 20:57:38] "GET / HTTP/1.1" 500 0
Traceback (most recent call last):
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 266, in write
    "write() argument must be a bytes instance"
AssertionError: write() argument must be a bytes instance
127.0.0.1 - - [26/Apr/2019 20:57:38] "GET / HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 41378)
Traceback (most recent call last):
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 266, in write
    "write() argument must be a bytes instance"
AssertionError: write() argument must be a bytes instance

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 141, in run
    self.handle_error()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 368, in handle_error
    self.finish_response()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/simple_server.py", line 133, in handle
    handler.run(self.server.get_app())
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 144, in run
    self.close()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------
127.0.0.1 - - [26/Apr/2019 20:57:38] "GET / HTTP/1.1" 500 0
Traceback (most recent call last):
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 266, in write
    "write() argument must be a bytes instance"
AssertionError: write() argument must be a bytes instance
127.0.0.1 - - [26/Apr/2019 20:57:38] "GET / HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 41380)
Traceback (most recent call last):
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 266, in write
    "write() argument must be a bytes instance"
AssertionError: write() argument must be a bytes instance

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 141, in run
    self.handle_error()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 368, in handle_error
    self.finish_response()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/simple_server.py", line 133, in handle
    handler.run(self.server.get_app())
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 144, in run
    self.close()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------
127.0.0.1 - - [26/Apr/2019 20:57:38] "GET / HTTP/1.1" 500 0
Traceback (most recent call last):
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 266, in write
    "write() argument must be a bytes instance"
AssertionError: write() argument must be a bytes instance
127.0.0.1 - - [26/Apr/2019 20:57:38] "GET / HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 41382)
Traceback (most recent call last):
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 266, in write
    "write() argument must be a bytes instance"
AssertionError: write() argument must be a bytes instance

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 141, in run
    self.handle_error()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 368, in handle_error
    self.finish_response()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/simple_server.py", line 133, in handle
    handler.run(self.server.get_app())
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 144, in run
    self.close()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------
127.0.0.1 - - [26/Apr/2019 20:57:38] "GET / HTTP/1.1" 500 0
Traceback (most recent call last):
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 266, in write
    "write() argument must be a bytes instance"
AssertionError: write() argument must be a bytes instance
127.0.0.1 - - [26/Apr/2019 20:57:38] "GET / HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 41384)
Traceback (most recent call last):
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 266, in write
    "write() argument must be a bytes instance"
AssertionError: write() argument must be a bytes instance

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 141, in run
    self.handle_error()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 368, in handle_error
    self.finish_response()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/simple_server.py", line 133, in handle
    handler.run(self.server.get_app())
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 144, in run
    self.close()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------
127.0.0.1 - - [26/Apr/2019 20:57:38] "GET / HTTP/1.1" 500 0
Traceback (most recent call last):
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 266, in write
    "write() argument must be a bytes instance"
AssertionError: write() argument must be a bytes instance
127.0.0.1 - - [26/Apr/2019 20:57:38] "GET / HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 41386)
Traceback (most recent call last):
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 266, in write
    "write() argument must be a bytes instance"
AssertionError: write() argument must be a bytes instance

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 141, in run
    self.handle_error()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 368, in handle_error
    self.finish_response()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/simple_server.py", line 133, in handle
    handler.run(self.server.get_app())
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/handlers.py", line 144, in run
    self.close()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/wsgiref/simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------
^CTraceback (most recent call last):
  File "middleware.py", line 59, in <module>
    srv.serve_forever()
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/socketserver.py", line 232, in serve_forever
    ready = selector.select(poll_interval)
  File "/home/george/.pyenv/versions/3.7.3/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt
george@Xubuntu1804:~/Desktop/desktop/django_code/wsgi_test$ 
